services:
  strapi-next-ecommerce-backend:
    build: .
    ports:
      - '1337:1337'
    depends_on:
      - strapi-next-ecommerce-postgres

  strapi-next-ecommerce-postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=strapi

networks:
  default:
    name: strapi-next-ecommerce-backend
